return {}
-- local M = {
--   "nvim-lualine/lualine.nvim",
--   dependencies = { "nvim-tree/nvim-web-devicons", "catppuccin/nvim" },
-- }
--
-- function M.config()
--   require("lualine").setup({
--     options = {
--       icons_enabled = true,
--       theme = "auto",
--       transparent = true,
--       component_separators = { left = "", right = "" },
--       section_separators = { left = "", right = "" },
--       disabled_filetypes = {
--         statusline = {},
--         winbar = {},
--       },
--       ignore_focus = {},
--       always_divide_middle = true,
--       always_show_tabline = true,
--       globalstatus = true,
--       refresh = {
--         statusline = 100,
--         tabline = 100,
--         winbar = 100,
--       },
--     },
--     sections = {
--       lualine_a = {
--         {
--           "mode",
--           separator = { left = " ", right = "" },
--           right_padding = 2,
--         },
--       },
--       lualine_b = { "filename", "branch", "diff", "diagnostics" },
--       lualine_c = { "%=", color = { bg = nil } },
--       lualine_x = { color = { bg = nil } },
--       lualine_y = { "filetype", "progress" },
--       lualine_z = { { "location", separator = { left = "", right = "" }, left_padding = 2 } },
--     },
--     inactive_sections = {
--       lualine_a = { "filename" },
--       lualine_b = {},
--       lualine_c = {},
--       lualine_x = {},
--       lualine_y = {},
--       lualine_z = { "location" },
--     },
--     tabline = {},
--     -- winbar = {},
--     -- inactive_winbar = {},
--     extensions = {},
--   })
-- end
--
-- return M
